import { createClient } from '@sanity/client';
import { createImageUrlBuilder } from '@sanity/image-url';
import type { Flower } from '../types/flower';

const projectId = import.meta.env.PUBLIC_SANITY_PROJECT_ID || 'k71savps';
const dataset = import.meta.env.PUBLIC_SANITY_DATASET || 'production';
const apiVersion = import.meta.env.PUBLIC_SANITY_API_VERSION || '2024-03-01';

export const sanityClient = createClient({
  projectId,
  dataset,
  apiVersion,
  useCdn: false,
});

const builder = createImageUrlBuilder(sanityClient);

export function urlFor(source: any) {
  if (!source || !source.asset) {
    return 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=600&q=80&fm=webp';
  }
  return builder.image(source).auto('format').fit('max').width(600).url();
}

export const MOCK_FLOWERS: Flower[] = [
  {
    _id: 'flower-1',
    name: 'Velvet Romance Rose Bouquet',
    slug: { current: 'velvet-romance-rose-bouquet' },
    description: 'A breathtaking arrangement of 24 premium deep red Ecuador roses intertwined with silver dollar eucalyptus and baby’s breath. Perfect for expressing passionate love and unforgettable anniversaries.',
    image: 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 89.99,
    oldPrice: 109.99,
    category: 'roses',
    featured: true,
    bestSeller: true,
    stock: 15,
    colors: ['Deep Red', 'Crimson', 'Ruby'],
    flowerType: 'Ecuador Red Roses',
    careInstructions: 'Trim stems at a 45-degree angle under lukewarm water. Place in clean water with floral food provided. Refresh water every 2 days and keep out of direct sunlight.',
    deliveryInformation: 'Same-day flower delivery available for orders placed before 2:00 PM. Packaged with hydration gel pack for maximum freshness.',
    createdAt: '2026-01-10T10:00:00Z',
    rating: 4.9,
    reviewsCount: 128,
  },
  {
    _id: 'flower-2',
    name: 'Pastel Meadow Peony Dream',
    slug: { current: 'pastel-meadow-peony-dream' },
    description: 'An enchanting mix of blush pink peonies, soft lavender hydrangeas, white ranunculus, and delicate astilbe wrapped in natural eco kraft paper.',
    image: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 78.50,
    oldPrice: 92.00,
    category: 'bouquets',
    featured: true,
    bestSeller: true,
    stock: 10,
    colors: ['Blush Pink', 'Soft Lavender', 'Cream White'],
    flowerType: 'Peonies & Hydrangeas',
    careInstructions: 'Keep vase filled with cool water. Peonies open quickly in warm rooms; keep in cool temperature overnight.',
    deliveryInformation: 'Express morning delivery available. Comes with handcrafted greeting card.',
    createdAt: '2026-01-12T10:00:00Z',
    rating: 4.95,
    reviewsCount: 94,
  },
  {
    _id: 'flower-3',
    name: 'Golden Sunburst Sunflower Arrangement',
    slug: { current: 'golden-sunburst-sunflower-arrangement' },
    description: 'Brighten anyone’s day with radiant golden sunflowers, yellow spray roses, solidago, and fresh hypericum berries in a rustic burlap tied arrangement.',
    image: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 54.99,
    oldPrice: 65.00,
    category: 'birthday',
    featured: true,
    bestSeller: false,
    stock: 25,
    colors: ['Golden Yellow', 'Warm Amber'],
    flowerType: 'Sunflowers',
    careInstructions: 'Sunflowers love heavy water. Fill vase to 3/4 depth and replace water daily.',
    deliveryInformation: 'Standard next-day delivery nationwide in temperature-controlled boxes.',
    createdAt: '2026-01-15T10:00:00Z',
    rating: 4.8,
    reviewsCount: 76,
  },
  {
    _id: 'flower-4',
    name: 'Royal Orchid Elegance Bowl',
    slug: { current: 'royal-orchid-elegance-bowl' },
    description: 'Exquisite double-stemmed Phalaenopsis white orchid planted in a sleek ceramic matte bowl with decorative river stones and moss finish.',
    image: 'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 110.00,
    oldPrice: 130.00,
    category: 'plants',
    featured: false,
    bestSeller: true,
    stock: 8,
    colors: ['Pure White', 'Emerald Green'],
    flowerType: 'Phalaenopsis Orchid',
    careInstructions: 'Water once per week with 3 ice cubes at the base. Place in bright indirect lighting.',
    deliveryInformation: 'Hand-delivered by specialized floral courier to ensure no stem damage.',
    createdAt: '2026-01-18T10:00:00Z',
    rating: 5.0,
    reviewsCount: 42,
  },
  {
    _id: 'flower-5',
    name: 'Whispering Lilies & White Roses',
    slug: { current: 'whispering-lilies-white-roses' },
    description: 'Graceful Casablanca white lilies combined with Avalanche white roses and plumosus fern, symbolising purity, peace, and eternal elegance.',
    image: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 95.00,
    oldPrice: 115.00,
    category: 'wedding',
    featured: true,
    bestSeller: false,
    stock: 12,
    colors: ['Ivory White', 'Sage Green'],
    flowerType: 'Casablanca Lilies & White Roses',
    careInstructions: 'Gently snip off yellow pollen stamens to prevent petal staining as lilies open.',
    deliveryInformation: 'Delivered in bloom-shield protective wrapping.',
    createdAt: '2026-01-20T10:00:00Z',
    rating: 4.88,
    reviewsCount: 65,
  },
  {
    _id: 'flower-6',
    name: 'Sweet Anniversary Blush Tulips',
    slug: { current: 'sweet-anniversary-blush-tulips' },
    description: 'Fresh crisp Dutch tulips in soft blush pink, peach, and coral hues. Carefully hand-wrapped with silk satin ribbon.',
    image: 'https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 68.00,
    oldPrice: 79.99,
    category: 'anniversary',
    featured: false,
    bestSeller: true,
    stock: 18,
    colors: ['Blush Pink', 'Coral', 'Peach'],
    flowerType: 'Dutch Tulips',
    careInstructions: 'Tulips continue to grow in the vase! Keep water icy cold to prolong vase life.',
    deliveryInformation: 'Same day delivery in premium signature Bloomify box.',
    createdAt: '2026-01-22T10:00:00Z',
    rating: 4.92,
    reviewsCount: 110,
  },
  {
    _id: 'flower-7',
    name: 'Rustic Wildflower Sunset',
    slug: { current: 'rustic-wildflower-sunset' },
    description: 'An organic, boho-chic arrangement featuring dried pampas grass, terracotta spray carnations, eryngium thistles, and dusty miller.',
    image: 'https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 72.00,
    oldPrice: 85.00,
    category: 'bouquets',
    featured: false,
    bestSeller: false,
    stock: 14,
    colors: ['Terracotta', 'Dusty Blue', 'Sand'],
    flowerType: 'Wildflowers & Everlastings',
    careInstructions: 'Low maintenance arrangement. Spritz foliage lightly or enjoy long-lasting bloom life.',
    deliveryInformation: 'Safely shipped in eco-friendly protective packaging.',
    createdAt: '2026-01-25T10:00:00Z',
    rating: 4.75,
    reviewsCount: 38,
  },
  {
    _id: 'flower-8',
    name: 'Monstera Deliciosa Botanica Plant',
    slug: { current: 'monstera-deliciosa-botanica-plant' },
    description: 'Lush tropical Swiss Cheese Plant potted in a premium terracotta container. Air-purifying and perfect for modern home interiors.',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=600&q=80&fm=webp',
    price: 49.99,
    oldPrice: 59.99,
    category: 'plants',
    featured: false,
    bestSeller: false,
    stock: 20,
    colors: ['Deep Green'],
    flowerType: 'Monstera Plant',
    careInstructions: 'Water when top 2 inches of soil feel dry. Wipe leaves occasionally to remove dust.',
    deliveryInformation: 'Potted and carefully secured with root stabilization mesh.',
    createdAt: '2026-01-28T10:00:00Z',
    rating: 4.85,
    reviewsCount: 84,
  }
];
